### ISSUE TITLE
Error when generating json for D365 CSDL

### ISSUE THREAD

**Issue by ciaomatteo** [oasis-tcs/odata-json-schema#1]
Hi
When I try to convert a Dynamics 365 CSDL file, I get this error message:
`..\examples\metadata.xml
lexical error: malformed number, a digit is required after the exponent.
                                        ta#sdkmessageprocessingstepsec
                     (right here) ------^`
Please let me know if you need more details.

**Comment by ralfhandl** [comment]
Hi,

Ideal would be if you can send me a $metadata file that produces this error.

Thanks in advance
Ralf

**Comment by ciaomatteo** [comment]
Thanks for helping me out. It’s not exactly the same file, but it should provoke the same error message. It’s the Standard D365 metadata file (see attachment).
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#csdl-metadata-document

Best Regards
Mattias

**Comment by ciaomatteo** [comment]
[$metadata.txt](https://github.com/oasis-tcs/odata-json-schema/files/2339310/metadata.txt)
Sorry, this time with attachment. Please rename file to .xml.
Thanks!

**Comment by ralfhandl** [comment]
Hi Mattias,

Problem was that the D365 is invalid: it uses Scale="Variable", it should (actually MUST) use Scale="variable" with a lowercase value.

As I can't fix Dynamics 365 I relaxed the script a little: https://github.com/oasis-tcs/odata-json-schema/commit/746ac66352b48c183c7de7fbd23ec8f85469d173 

Just out of curiosity: what are you going to do with the JSON Schema file?

Thanks
Ralf

**Comment by ciaomatteo** [comment]
Perfect, I will give it a try on Monday. Thanks for adapting to the D365 version.
We are going to integrate D365 with other custom applications. The plan is to use JSON Schema to validate and possibly generate POJO's for data exchange. Do you think this is a viable approach?

**Comment by mikepizzo** [comment]
More info; the issue is introduced by the underlying .Net OData Library.  Opened an [issue](https://github.com/OData/odata.net/issues/1243) to track, but don't know how we can fix without introducing a breaking change.  Note that OData Library does read this case-insensitive, so should work with payloads generated using either casing.

**Comment by ciaomatteo** [comment]
JSON Schema generation works fine now. Thanks for your support @ralfhandl, @mikepizzo.
