### ISSUE TITLE
OData json schema doesn't explicitly mention $Kind for entityset container.

### ISSUE THREAD

**Issue by xuzhg** [oasis-tcs/odata-json-schema#2]
Hi, 

OData json-schema "http://docs.oasis-open.org/odata/odata-csdl-json/v4.01/cs01/odata-csdl-json-v4.01-cs01.html#_Toc501463222" has the following information:

 
13    Entity Container

...
Entity Container Object

An entity container is represented as a member of the schema object whose name is the unqualified name of the entity container and whose value is an object.

The entity container object MAY contain the member $Extends, members representing entity sets, singletons, action imports, and function imports, as well as annotations.
 
However, There's no sentence to mention that the Entity container object MUST or May include the member $Kind with a string value of EntityContainer. 

But, in the example, you can find "$Kind": "EntityContainer", did i miss something?

**Comment by ralfhandl** [comment]
Hi Sam,

You're totally right, that sentence somehow got lost, and we'll add it in.

Thanks for catching this!
Ralf

**Comment by xuzhg** [comment]
@ralfhandl Thanks for your response. I have another concern about the Record expression. 

From JSON spec: 

14.4.12 Record
The record expression enables a new entity type or complex type instance to be constructed.

A record expression MAY specify the structured type of its result, which MUST be an entity type or complex type in scope. If not explicitly specified, the type is derived from the expression’s context.

...

### But, it seems the spec doesn't mention the $Type in record object:

=============
Record expressions are represented as objects with one member per property value expression. The member name is the property name, and the member value is the property value expression.

It MAY contain annotations for itself and its members. Annotations for record members are prefixed with the member name.

### besides, From the XML spec,  record has "type" attribute:

```C#
Attribute Type

The value of Type is the qualified name of a structured type in scope.
```

So far clarification, it's better to explicitly add a sentence to describe how to type in the record json expression.

**Comment by ralfhandl** [comment]
Hi @xuzhg, this has been added with https://issues.oasis-open.org/browse/ODATA-1170.

> The type of a record expression is represented as the @type control information, see  [OData JSON].

```json
"@person.Employee": {
  "@type": "https://example.org/vocabs/person#org.example.person.Manager",
```

**Comment by ralfhandl** [comment]
@xuzhg please use the repository https://github.com/oasis-tcs/odata-csdl-schemas for issues regarding CSDL (JSON or XML).

This repository has a different purpose.
