### ISSUE TITLE
qualifier in the external annotation

### ISSUE THREAD

**Issue by xuzhg** [oasis-tcs/odata-json-schema#3]
In the JSON Schema document, an example confuses me.

5.2 Annotations with External Targeting
$Annotations

The value of $Annotations is an object with one member per annotation target. The member name is a path identifying the annotation target, the member value is an object containing annotations for that target.

Example 7: annotations targeting the Person type with qualifier Tablet

```json
"org.example": {

  "$Annotations": {

    "org.example.Person#Tablet": {

      …

    }

  }
```

Form the description "The member name is a path identifying the annotation target", so, the name in the example 7 should be "org.example.Person", not the "org.example.Person#Tablet", Right?

Maybe i confuse the "qualifier". But, in my understanding, qualifier is used in the embedded annotation name as below:

```json

"org.example": {
  "$Annotations": {
    "org.example.Person": {
      "@UI.DisplayName#Tablet": {
           "$Path": "FirstName"
       ...
}
```

**Comment by ralfhandl** [comment]
You are correct, and the example has already been fixed. It now reads
```json
"org.example": {
  "$Alias": "self", 
  "$Annotations": {
    "self.Person": {
      "@Core.Description#Tablet": "Dummy",
      …
    }
  } 
},
```
The qualifier is appended to the term name, not the annotation target.

**Comment by ralfhandl** [comment]
@xuzhg please use the repository https://github.com/oasis-tcs/odata-csdl-schemas for issues regarding CSDL (JSON or XML).

This repository has a different purpose.
